### PR TITLE
reconfigure i18n context

### PR DESCRIPTION
**Pull request by romeboards**
This tweaks the integration in order to address https://github.com/mccrodp/gatsby-starter-contentful-i18n/issues/6

### CODE REVIEW

**Comment by mccrodp** [comment]
Nice solution, looking clean, love the use of module loader there to simplify things. Going to test it out later today and hopefully get this merged in. Really appreciated! 😄

**Comment by romeboards** [comment]
No problem! Happy to share our project repo once it launches later this week if its useful.

**Comment by mccrodp** [comment]
Absolutely, I'll link out to it from the README even if you like to create an Examples in the Wild section or similar via PR. Will add my own there once completed also ;)

**Review by mccrodp — APPROVED** [review]
Perfect, working 🚀

**Pull request merged**
